"""
deltacert.validation.harness
============================

ONE result schema for all 20 collectors + generators for the 4 output tables.

Every validation run — Tier A flagship or Tier C coverage row — produces a
result.json in the SAME schema. Flagships fill more optional fields
(trajectory, latency, plots); Tier C fills the minimum. The 4 tables are
generated FROM the result files, never hand-written:

    TABLE 1  killer chart        (Tier A rows only)        → README / launch
    TABLE 2  full matrix         (all 20)                  → master summary
    TABLE 3  trajectory table    (runs with trajectory)    → long-horizon proof
    TABLE 4  calibration table   (d vs downstream, all)    → tau is actionable

Design rules (same philosophy as collectors.py):
  * NO simulation. This module never invents numbers — it validates and
    formats numbers produced by real collector runs. A result.json missing
    required fields is REJECTED, not defaulted.
  * verdict is DERIVED from d_comm vs tau at load time and cross-checked
    against the stored value — a hand-edited verdict that contradicts the
    math hard-fails. The tables cannot disagree with the certificates.
  * Every result must reference its cert.json — a validation row without a
    certificate behind it is not evidence.
  * short_eval: optional block recording what a standard benchmark (HumanEval,
    MMLU, GSM8K) said about the SAME change. Required to claim "DeltaCert
    caught what evals missed."

Layout convention:
    validation/
      kv_cache_quant/
        result.json          <- this schema
        cert.json            <- real deltacert certificate
        run.py               <- exact commands a company would run
        plots/…
      …
      tables/                <- generated by build_all_tables()
        killer_chart.md
        full_matrix.md
        trajectory_table.md
        calibration_table.md

Usage:
    from deltacert.validation.harness import ValidationResult, save_result, build_all_tables

    res = ValidationResult(
        collector="kv_cache_quant", tier="A",
        run_id="2026-07-04_kv8_run1",
        change={"baseline": "Llama-3.1-8B fp16 KV",
                "candidate": "Llama-3.1-8B int8 KV",
                "change_type": "kv_cache_quant"},
        business_goal={"reason": "2x batch size / less VRAM",
                       "expected_gain": {"throughput_x": 1.9}},
        workload={"task_family": "coding_agent", "dataset": "canaries_v1",
                  "num_prompts": 50, "context_length": 8192},
        metrics={"d_comm": 3.41, "tau": 3.0,
                 "downstream_delta": {"pass_at_1_drop_pct": 0.4}},
        decision_statement="KV-int8 certified safe for coding workload ...",
        cert_path="validation/kv_cache_quant/cert.json",
    )
    save_result(res, "validation/kv_cache_quant/result.json")
    build_all_tables("validation", out_dir="validation/tables")
"""

from __future__ import annotations

import glob
import json
import math
import os
from dataclasses import dataclass, field, asdict
from typing import List, Optional

__all__ = [
    "SchemaError",
    "ValidationResult",
    "save_result",
    "load_result",
    "load_all_results",
    "build_killer_chart",
    "build_full_matrix",
    "build_trajectory_table",
    "build_calibration_table",
    "build_all_tables",
]

VALID_COLLECTORS = {
    "allreduce_tp", "alltoall_ep", "pipeline_parallel", "kv_transfer",
    "weight_quant", "kv_cache_quant", "activation_quant", "gradient_compress",
    "lora", "prefix_cache", "engine_swap", "batch_divergence", "spec_decoding",
    "sparse_attention", "moe_token_dropping", "neuron_skipping",
    "model_swap", "provider_drift", "prompt_swap", "trajectory",
}
VALID_TIERS = {"A", "B", "C"}
DEFAULT_TAU = 3.0


class SchemaError(ValueError):
    """A result file violates the schema. Reject — never default around it."""


# ─────────────────────────────────────────────────────────────────────────────
# Schema
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class ValidationResult:
    # ── required for every tier ───────────────────────────────────────────────
    collector: str
    tier: str
    run_id: str
    change: dict            # {baseline, candidate, change_type}
    business_goal: dict     # {reason, expected_gain?}
    workload: dict          # {task_family, num_prompts, dataset?, ...}
    metrics: dict           # {d_comm, tau, downstream_delta{...}, ...}
    decision_statement: str
    cert_path: str          # path to the real cert.json behind this row

    # ── optional (flagships fill these) ───────────────────────────────────────
    status: str = "completed"
    artifacts: dict = field(default_factory=dict)   # plot paths etc.
    notes: dict = field(default_factory=dict)       # incident ref, hardware, seed

    # ------------------------------------------------------------------ core
    def validate(self) -> "ValidationResult":
        if self.collector not in VALID_COLLECTORS:
            raise SchemaError(
                f"Unknown collector '{self.collector}'. "
                f"Valid: {sorted(VALID_COLLECTORS)}"
            )
        if self.tier not in VALID_TIERS:
            raise SchemaError(f"tier must be one of {sorted(VALID_TIERS)}, got '{self.tier}'")
        if not self.run_id or not str(self.run_id).strip():
            raise SchemaError("run_id is required.")

        # change block
        for key in ("baseline", "candidate", "change_type"):
            if not self.change.get(key):
                raise SchemaError(f"change.{key} is required — a validation row "
                                  "must state exactly what changed.")

        # business goal
        if not self.business_goal.get("reason"):
            raise SchemaError("business_goal.reason is required — every row must "
                              "say WHY a company would make this change.")

        # workload
        if not self.workload.get("task_family"):
            raise SchemaError("workload.task_family is required.")
        n = self.workload.get("num_prompts")
        if not isinstance(n, int) or n <= 0:
            raise SchemaError("workload.num_prompts must be a positive int — a "
                              "row with zero measurements is not evidence.")

        # metrics
        d = self.metrics.get("d_comm")
        if d is None:
            raise SchemaError("metrics.d_comm is required.")
        if isinstance(d, str):
            if d != "inf":
                raise SchemaError(f"metrics.d_comm string value must be 'inf', got '{d}'.")
            d_val = math.inf
        else:
            d_val = float(d)
            if math.isnan(d_val):
                raise SchemaError("metrics.d_comm is NaN — measurement is broken, "
                                  "do not record this row.")
        tau = float(self.metrics.get("tau", DEFAULT_TAU))
        if tau <= 0:
            raise SchemaError("metrics.tau must be positive.")

        # verdict: derived from the math; stored verdict must AGREE
        derived = "safe" if d_val >= tau else "unsafe"
        stored = self.metrics.get("verdict")
        if stored is None:
            self.metrics["verdict"] = derived
        elif stored != derived:
            raise SchemaError(
                f"Stored verdict '{stored}' contradicts d_comm={d} vs tau={tau} "
                f"(derived '{derived}'). Verdicts are computed, not chosen — "
                "fix the metrics or delete the row."
            )

        # downstream evidence: required so tables can show d → reality mapping
        dd = self.metrics.get("downstream_delta")
        if not isinstance(dd, dict) or not dd:
            raise SchemaError(
                "metrics.downstream_delta is required (at least one measured "
                "downstream number, e.g. {'task_success_drop_pct': 1.8}). "
                "Without it the row cannot support the d→reality claim."
            )
        for k, v in dd.items():
            if not isinstance(v, (int, float)) or math.isnan(float(v)):
                raise SchemaError(f"downstream_delta['{k}'] must be a finite number.")

        # false_safe_single_position: the single-position certificate said
        # "safe" (d_comm >= tau) but the REAL measured downstream delta shows
        # material damage (> 2 pts, same convention as build_calibration_table's
        # "materially degraded" bar). This is the exact failure mode the
        # fail-closed architecture exists to prevent — stamped explicitly so a
        # row can never silently read as "safe...completed" while its own
        # downstream_delta contradicts that. True horizon-blindness (the
        # single canary position didn't see damage that only appears over a
        # full generation) is a DIFFERENT claim than a wrong formula; this
        # flag documents which one occurred without editorializing in the
        # decision_statement.
        worst_drop = max(abs(float(v)) for v in dd.values())
        self.metrics["false_safe_single_position"] = (
            self.metrics["verdict"] == "safe" and worst_drop > 2.0
        )

        # flagship_verdict: the row's headline, ACTIONABLE call — distinct
        # from metrics.verdict, which is purely the computed d_comm-vs-tau
        # result and must stay mathematically honest (it's what the
        # certificate actually measured at the position(s) it looked at).
        # When a false_safe_single_position is caught, the certificate was
        # right about what it measured and wrong about being sufficient
        # evidence — the flagship call a reader/deployer should act on flips
        # to "unsafe", set by the downstream evidence, while metrics.verdict
        # keeps recording what the single-position math actually said. This
        # is what prevents a row from reading as "SAFE — enable fleet-wide"
        # while its own downstream_delta shows the deployment was destroyed.
        self.metrics["flagship_verdict"] = (
            "unsafe" if self.metrics["false_safe_single_position"]
            else self.metrics["verdict"]
        )

        # trajectory sub-block, if present, has its own required fields
        traj = self.metrics.get("trajectory")
        if traj is not None:
            if not traj.get("measured"):
                raise SchemaError("metrics.trajectory present but measured is not true.")
            if "safe_until_token" not in traj:
                raise SchemaError("metrics.trajectory requires safe_until_token.")

        # short_eval sub-block: what a standard benchmark said about this same
        # change — required to claim "caught what evals missed" (result E)
        se = self.metrics.get("short_eval")
        if se is not None:
            if not se.get("benchmark"):
                raise SchemaError("metrics.short_eval requires 'benchmark'.")
            if "delta_pct" not in se or not isinstance(se["delta_pct"], (int, float)):
                raise SchemaError("metrics.short_eval requires numeric 'delta_pct'.")
            if se.get("verdict_by_benchmark") not in ("looks_safe", "looks_unsafe"):
                raise SchemaError(
                    "metrics.short_eval.verdict_by_benchmark must be "
                    "'looks_safe' or 'looks_unsafe'.")

        # per_domain sub-block: if the run used domain-tagged canaries, the
        # certified d_comm MUST be the worst-domain value, never a blended
        # average — same "don't average away the failure" rule as trajectory's
        # d_min. Prevents a future script from silently regressing to blended
        # averaging while still claiming domain-stratified evidence.
        pd = self.metrics.get("per_domain")
        if pd is not None:
            if not isinstance(pd, dict) or len(pd) < 2:
                raise SchemaError(
                    "metrics.per_domain must be a dict of {domain: d_comm} "
                    "with at least 2 domains — a single-domain block provides "
                    "no stratification and should just be omitted."
                )
            domain_vals = []
            for domain, dv in pd.items():
                if isinstance(dv, str):
                    if dv != "inf":
                        raise SchemaError(f"per_domain['{domain}'] string value must be 'inf', got '{dv}'.")
                    domain_vals.append(math.inf)
                else:
                    fv = float(dv)
                    if math.isnan(fv):
                        raise SchemaError(f"per_domain['{domain}'] is NaN — broken measurement.")
                    domain_vals.append(fv)
            worst = min(domain_vals)
            if not (math.isinf(worst) and math.isinf(d_val)) and abs(worst - d_val) > 0.01:
                raise SchemaError(
                    f"metrics.d_comm={d_val} does not match the worst per_domain "
                    f"value={worst}. The certified d_comm for a domain-tagged run "
                    "MUST be the worst-domain value, not a blended average — "
                    "fix the metrics, don't silently average away a regression."
                )

        # decision + certificate linkage
        if not self.decision_statement or len(self.decision_statement.strip()) < 20:
            raise SchemaError(
                "decision_statement is required and must be a real sentence a "
                "company can act on (>= 20 chars)."
            )
        if not self.cert_path:
            raise SchemaError("cert_path is required — every validation row must "
                              "point at the certificate that backs it.")
        return self

    # ---------------------------------------------------------------- helpers
    @property
    def d_value(self) -> float:
        d = self.metrics["d_comm"]
        return math.inf if d == "inf" else float(d)

    @property
    def verdict(self) -> str:
        return self.metrics["verdict"]

    def d_display(self) -> str:
        if math.isinf(self.d_value):
            return "inf"
        d = self.d_value + 0.0  # normalize -0.0 -> 0.0 for display
        return f"{d:.2f}"

    def primary_downstream(self) -> str:
        dd = self.metrics["downstream_delta"]
        k, v = next(iter(dd.items()))
        return f"{k}={v:+.1f}"

    def gain_display(self) -> str:
        g = self.business_goal.get("expected_gain") or {}
        if not g:
            return self.business_goal.get("reason", "-")
        parts = []
        for k, v in g.items():
            if k.endswith("_x"):
                parts.append(f"{v}x {k[:-2].replace('_', ' ')}")
            elif k.endswith("_pct"):
                parts.append(f"{v:+.0f}% {k[:-4].replace('_', ' ')}")
            else:
                parts.append(f"{k}={v}")
        return ", ".join(parts)


# ─────────────────────────────────────────────────────────────────────────────
# Save / load
# ─────────────────────────────────────────────────────────────────────────────

def save_result(result: ValidationResult, path: str) -> str:
    result.validate()
    if not os.path.exists(result.cert_path):
        raise SchemaError(
            f"cert_path '{result.cert_path}' does not exist. Run the collector "
            "and produce the certificate BEFORE recording the validation row."
        )
    with open(result.cert_path, encoding="utf-8") as f:
        cert = json.load(f)
    layer = cert.get("layers", {}).get(result.change.get("change_type")) \
            or next(iter(cert.get("layers", {}).values()), None)
    if layer and layer.get("d_comm") is not None:
        cert_d = math.inf if layer["d_comm"] == "inf" else float(layer["d_comm"])
        if not (math.isinf(cert_d) and math.isinf(result.d_value)) \
           and abs(cert_d - result.d_value) > 0.01:
            raise SchemaError(
                f"result.json d_comm={result.d_value} does not match the "
                f"certificate's d_comm={cert_d} at {result.cert_path}. The "
                "validation row must transcribe the certificate, not restate it.")
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(asdict(result), f, indent=2)
    return path


def load_result(path: str) -> ValidationResult:
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    known = {f_.name for f_ in ValidationResult.__dataclass_fields__.values()}  # type: ignore[attr-defined]
    unknown = set(data) - known
    if unknown:
        raise SchemaError(f"{path}: unknown schema fields {sorted(unknown)}.")
    try:
        result = ValidationResult(**data)
    except TypeError as e:
        raise SchemaError(f"{path}: missing required fields ({e}).") from e
    return result.validate()


def load_all_results(validation_dir: str) -> List[ValidationResult]:
    paths = sorted(glob.glob(os.path.join(validation_dir, "*", "result.json")))
    if not paths:
        raise SchemaError(
            f"No result.json files found under '{validation_dir}/*/'. "
            "Nothing to tabulate."
        )
    results = [load_result(p) for p in paths]
    seen = {}
    for r in results:
        if r.collector in seen:
            raise SchemaError(
                f"Duplicate collector '{r.collector}' in results "
                f"(run_ids: {seen[r.collector]}, {r.run_id}). One canonical "
                "row per collector — archive superseded runs elsewhere."
            )
        seen[r.collector] = r.run_id
    return results


# ─────────────────────────────────────────────────────────────────────────────
# TABLE 1 — Killer chart (Tier A only)
# ─────────────────────────────────────────────────────────────────────────────

def build_killer_chart(results: List[ValidationResult]) -> str:
    rows = [r for r in results if r.tier == "A"]
    if not rows:
        raise SchemaError("Killer chart requires at least one Tier A result.")
    lines = [
        "| Change | Business gain | d_COMM | Downstream effect | Verdict |",
        "|---|---|---|---|---|",
    ]
    for r in sorted(rows, key=lambda x: x.collector):
        change = f"{r.change['baseline']} → {r.change['candidate']}"
        verdict = "✅ Safe" if r.verdict == "safe" else "❌ Unsafe"
        lines.append(
            f"| {change} | {r.gain_display()} | {r.d_display()} "
            f"| {r.primary_downstream()} | {verdict} |"
        )
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# TABLE 2 — Full validation matrix (all collectors)
# ─────────────────────────────────────────────────────────────────────────────

def build_full_matrix(results: List[ValidationResult]) -> str:
    lines = [
        "| Collector | Tier | Change | d_COMM | Downstream delta | Verdict | Why a company does this |",
        "|---|---|---|---|---|---|---|",
    ]
    tier_order = {"A": 0, "B": 1, "C": 2}
    for r in sorted(results, key=lambda x: (tier_order[x.tier], x.collector)):
        change = f"{r.change['change_type']}"
        lines.append(
            f"| {r.collector} | {r.tier} | {change} | {r.d_display()} "
            f"| {r.primary_downstream()} | {r.verdict} "
            f"| {r.business_goal['reason']} |"
        )
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# TABLE 3 — Trajectory table (runs with trajectory measurements)
# ─────────────────────────────────────────────────────────────────────────────

def build_trajectory_table(results: List[ValidationResult]) -> str:
    rows = [r for r in results if r.metrics.get("trajectory")]
    if not rows:
        return ("_No trajectory measurements recorded yet. Run the trajectory "
                "flagship (collector 20) to populate this table._")
    lines = [
        "| Config | Short eval said | d_COMM | safe_until_token | failure_after_token | Verdict |",
        "|---|---|---|---|---|---|",
    ]
    for r in sorted(rows, key=lambda x: x.collector):
        t = r.metrics["trajectory"]
        se = r.metrics.get("short_eval")
        se_str = (f"{se['benchmark']} {se['delta_pct']:+.1f}% "
                  f"({se['verdict_by_benchmark'].replace('_', ' ')})" if se else "-")
        fail = t.get("failure_after_token", "-")
        lines.append(
            f"| {r.change['candidate']} | {se_str} | {r.d_display()} "
            f"| {t['safe_until_token']} | {fail} | {r.verdict} |"
        )
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# TABLE 4 — Calibration table (d vs downstream, does tau separate?)
# ─────────────────────────────────────────────────────────────────────────────

def build_calibration_table(results: List[ValidationResult]) -> str:
    lines = [
        "| Collector | d_COMM | tau | Verdict (from d) | Measured downstream delta | Evals missed it? | tau correct? |",
        "|---|---|---|---|---|---|---|",
    ]
    agreements = 0
    scored = 0
    n_caught = 0
    for r in sorted(results, key=lambda x: x.d_value, reverse=True):
        dd = r.metrics["downstream_delta"]
        # "materially degraded" heuristic for the agreement column: any
        # downstream drop metric worse than 2 percentage points. This is a
        # REPORTING convention, stated in the table header — the underlying
        # numbers are always shown so readers can apply their own bar.
        worst = max(abs(float(v)) for v in dd.values())
        actually_degraded = worst > 2.0
        predicted_degraded = r.verdict == "unsafe"
        agree = predicted_degraded == actually_degraded
        scored += 1
        agreements += int(agree)
        se = r.metrics.get("short_eval")
        caught = (se is not None
                  and se.get("verdict_by_benchmark") == "looks_safe"
                  and r.verdict == "unsafe"
                  and actually_degraded)
        if caught:
            n_caught += 1
        caught_str = "🎯 caught" if caught else ""
        lines.append(
            f"| {r.collector} | {r.d_display()} | {r.metrics.get('tau', DEFAULT_TAU)} "
            f"| {r.verdict} | {r.primary_downstream()} "
            f"| {caught_str} "
            f"| {'✅' if agree else '❌'} |"
        )
    lines.append("")
    lines.append(
        f"**tau agreement: {agreements}/{scored} rows** "
        "(convention: 'materially degraded' = any downstream drop > 2 pts; "
        "raw numbers shown so readers can apply their own bar)."
    )
    if n_caught:
        lines.append(
            f"\n**{n_caught} change(s) passed standard benchmarks but were correctly "
            "flagged unsafe by DeltaCert — and did degrade downstream.**")
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# Build everything
# ─────────────────────────────────────────────────────────────────────────────

def build_all_tables(validation_dir: str, out_dir: Optional[str] = None) -> dict:
    """Load every result.json under validation_dir and write the 4 tables.

    Returns {table_name: markdown_string}. If out_dir is given, also writes
    killer_chart.md, full_matrix.md, trajectory_table.md, calibration_table.md.
    """
    results = load_all_results(validation_dir)
    tables = {
        "killer_chart": build_killer_chart(results),
        "full_matrix": build_full_matrix(results),
        "trajectory_table": build_trajectory_table(results),
        "calibration_table": build_calibration_table(results),
    }
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
        for name, md in tables.items():
            with open(os.path.join(out_dir, f"{name}.md"), "w", encoding="utf-8") as f:
                f.write(f"<!-- generated by harness.build_all_tables — do not edit -->\n\n{md}\n")
    return tables


if __name__ == "__main__":
    import argparse
    import sys

    # Table content includes non-ASCII characters (e.g. the arrow in "batch=1
    # -> batch=64"). Windows consoles default to a legacy codepage (cp1252)
    # that can't encode them, crashing the print below with a raw
    # UnicodeEncodeError after the tables were already written successfully
    # to disk. Reconfigure stdout to UTF-8 first so console output matches
    # what's actually on disk; falls back silently on Python < 3.7 or a
    # stream that doesn't support reconfigure (e.g. captured/piped output).
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, ValueError):
        pass

    ap = argparse.ArgumentParser(description="Generate the 4 validation tables.")
    ap.add_argument("--validation-dir", default="validation")
    ap.add_argument("--out-dir", default="validation/tables")
    args = ap.parse_args()
    tables = build_all_tables(args.validation_dir, args.out_dir)
    print(f"Wrote 4 tables to {args.out_dir}/")
    print("\n" + tables["killer_chart"])
